In [3]:
import tensorflow as tf

In [6]:
print (tf.__version__)

2.8.0


In [7]:
# eager execution
x = [[1.]]
m = tf.matmul(x, x)
print(m)

tf.Tensor([[1.]], shape=(1, 1), dtype=float32)


2022-11-14 09:33:55.612709: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [9]:
x = tf.constant([[1,9],[3, 6]])
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 9],
       [3, 6]], dtype=int32)>

In [10]:
x = tf.add(x, 1)

In [11]:
print(x)

tf.Tensor(
[[ 2 10]
 [ 4  7]], shape=(2, 2), dtype=int32)
